# .streamlit/secrets.toml
SUPABASE_URL = "https://wwjzpcfrbyvjcsdffklv.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3anpwY2ZyYnl2amNzZGZma2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTY3NDcsImV4cCI6MjA3MzY3Mjc0N30.NtEgj3yyBon05eIhGINB0D5FyfF71ZsvGw0Cx0167dM"